### PR TITLE
Check for 1.53 support

### LINKED ISSUE #75: Can we lower the MSRV?
0.9 raised the MSRV to 1.56 by virtue of setting the edition to 2021. IMO it would be nice to avoid that for a while longer; for Quinn, for example, we have a policy of sticking to 6-month old versions for the MSRV.

### PR DESCRIPTION
**Pull request by djc**
Fixes #75.

### CODE REVIEW

**Comment by djc** [comment]
Would appreciate a release after this is merged.

**Review by est31 — CHANGES_REQUESTED** [review]
Can you add a changelog entry?

**Comment by djc** [comment]
Done.

**Review by est31 — APPROVED** [review]
Thanks!

**Pull request merged**
