### PR TITLE
Update RemoteKeyPair doc

### PR DESCRIPTION
**Pull request by nelson-ks**
Use "raw binary format" instead of "DER format" for clarity as mentioned in #83

### CODE REVIEW

**Comment by est31** [comment]
Can you link to the `KeyPair::public_key_raw` function and say it's the same format as exported there? "raw" on its own is a bit ambiguous.

**Comment by est31** [comment]
intra-doc-links work like this: https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html

**Comment by nelson-ks** [comment]
No problems. Yeah this is better.

**Review by est31 — APPROVED** [review]
Thanks!

**Pull request merged**
