### PR TITLE
Strip nanos from DateTime<Utc>

### LINKED ISSUE #44: DateTime nanoseconds not being stripped
It appears that `write_dt_utc_or_generalized()` is not stripping nanoseconds for `chrono::DateTime<Utc>`.

Simple example is as follows: 
```
// create certificate_params
...
let current_time = Utc::now();
// set not_before and not_after
...
// generate certificate
let cert = Certificate::from_params(certificate_params)?;

```
`libs.rs`:
```
fn write_dt_utc_or_generalized(writer: DERWriter, dt: &DateTime<Utc>) -> Result<(), RcgenError> {
    // RFC 5280 requires CAs to write certificate validity dates
    // below 2050 as UTCTime, and anything starting from 2050
    // as GeneralizedTime [1]. The RFC doesn't say anything
    // about dates before 1950, but as UTCTime can't represent
    // them, we have to use GeneralizedTime if we want to or not.
    // [1]: https://tools.ietf.org/html/rfc5280#section-4.1.2.5
    if (1950..2050).contains(&dt.year()) {
        let ut = UTCTime::from_datetime::<Utc>(dt); // fails here
        writer.write_utctime(&ut);
    } else {
        let gt = dt_to_generalized(dt)?;
        writer.write_generalized_time(&gt);
    }
    Ok(())
}
```

### PR DESCRIPTION
**Pull request by trevor-crypto**
When creating `CertificateParams` and using `DateTime<Utc>`, specifically
`chrono::Utc::now()`, the nanoseconds do not get stripped off before
attempting to call `UTCTime::from_datetime` (yasna), causing an error due to the ASN.1
standard

Closes #44

### CODE REVIEW

**Review by est31 — CHANGES_REQUESTED** [review]
Could you add a test? Also, maybe explain in the comment why stripping is not just useful for `GeneralizedTime` but also `UtcTime`.

**Comment by trevor-crypto** [comment]
> Could you add a test? Also, maybe explain in the comment why stripping is not just useful for `GeneralizedTime` but also `UtcTime`.

Sure thing

**Comment by trevor-crypto** [comment]
Writing the tests made me realize that `UTCTime` does not support leap seconds like `GeneralizedTime` does -- I noted this in the comments.

**Review by est31 — APPROVED** [review]
Thanks!

**Comment by est31** [comment]
@trevor-crypto I've merged your PR to the master branch. If you want me to make a release, please say say so.

**Comment by trevor-crypto** [comment]
> @trevor-crypto I've merged your PR to the master branch. If you want me to make a release, please say say so.

@est31 That would be great. Thank you!

**Pull request merged**
